name: Sync all branches
on:
  workflow_dispatch:

jobs:

  generate-matrix:
    name: Generate matrix of branches
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix of branches
        id: set-matrix
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${INPUT_UPSTREAM_REPOSITORY}.git"

          # these jq scripts will produce the same matrix jobs by default
          # choose the one that works for any additional values that you may need to build your matrix with
          jq_script='{ "branch": [inputs | split("\n") | .[] | gsub(".*refs/heads/"; "")] }'   # {"branch":["$branch_name_1","$branch_name_2"]}
          # jq_script='[inputs | split("\n") | .[] | gsub(".*refs/heads/"; "") | { "branch": . }]' # [{"branch":"$branch_name_1"},{"branch":"$branch_name_2"}]

          JSON="$(git ls-remote --heads "$upstream_repo" | jq -McnR "$jq_script")"

          # debug matrix pretty json formatted output
          jq --monochrome-output . -- <<< "$JSON"

          # set output variable named 'matrix' for use in subsequent jobs that 'needs' this job.
          # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_UPSTREAM_REPOSITORY: Toperlock/sing-box-subscribe

  sync_fork:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: Toperlock/sing-box-subscribe
          target_repository: 0x636f64655a/airflow
          upstream_branch: ${{ matrix.branch }}
          target_branch: ${{ matrix.branch }}
          force: true
          tags: true
